/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra210_2014_com_example_student_taskmanager_NativeClass */

#ifndef _Included_ra210_2014_com_example_student_taskmanager_NativeClass
#define _Included_ra210_2014_com_example_student_taskmanager_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra210_2014_com_example_student_taskmanager_NativeClass
 * Method:    percentageCalculation
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ra210_12014_com_example_student_taskmanager_NativeClass_percentageCalculation
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
